/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SwagLabs;



import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;



public class SwagLabsTest {
 WebDriver driver;
    @Test(priority = 1)
    public void homeTest() throws InterruptedException{
        WebDriverManager.chromedriver().setup();
         driver=new ChromeDriver();
        driver.manage().window().maximize();
        Home home= new Home(driver);
        boolean actual=home.getHome("https://www.saucedemo.com/");
        Assert.assertEquals(actual, true);
        
    }
    @Test(priority = 2)
    public void loginTest() throws InterruptedException{
        Login login= new Login(driver);
        boolean actual=login.loginCart("standard_user","secret_sauce");
        Assert.assertEquals(actual, true);
        
    }
    @Test(priority = 3)
    public void addToCartTest() throws InterruptedException{
        AddToCart add= new AddToCart(driver);
        boolean actual=add.addToCart("Sauce Labs Backpack");
        actual=add.addToCart("Sauce Labs Bolt T-Shirt");
        Assert.assertEquals(actual, true);
        
    }
    @Test(priority = 4)
    public void CheckoutTest() throws InterruptedException{
        Checkout check= new Checkout(driver);
        boolean actual= check.clickOnCart();     
        actual= check.checkout();        
        actual =check.address("Devdatta", "n", "111000");
        actual= check.order();         //7
        Assert.assertEquals(actual, true);
        driver.quit();
        
    }

   
}


