/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SwagLabs;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

public class AddToCart {

    WebDriver driver;
    public AddToCart(WebDriver driver){
       this.driver=driver;
    }

    public boolean addToCart(String product){
        boolean status=false;
        try{
        List<WebElement>list=driver.findElements(By.xpath("//div[@class='inventory_item_description']"));
        
        for(WebElement ele:list){
            String text=ele.findElement(By.xpath(".//div//a//div")).getText();
            if(text.equals(product)){
              WebElement addcartButton=ele.findElement(By.xpath(".//div//following::div[2]//button"));
               addcartButton.click();
               status=true;
            }
        }
       }catch(Exception e){
        System.out.println("failed with exception :"+e.getMessage());
        return status;
       }
        return status;
    }
    
}

